name: Terraform Step 1 Deployment & Destroy

on:
  push:
    paths:
      - 'step1/**'  # step1ディレクトリ内の変更がトリガー
  workflow_dispatch:  # 手動トリガー

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # pushイベントでのみデプロイを実行

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Terraformのセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4

      # 3. AWS認証の設定（必要な場合）
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # 4. step1のディレクトリで初期化
      - name: Terraform Init for Step1
        run: terraform init -reconfigure
        working-directory: step1

      # 5. step1用のplanを実行
      - name: Terraform Plan for Step1
        run: terraform plan
        working-directory: step1

      # 6. step1用のapplyを実行
      - name: Terraform Apply for Step1
        run: terraform apply -auto-approve
        working-directory: step1

  terraform-destroy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # 手動トリガーでのみdestroyを実行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4

      - name: Initialize Terraform
        run: terraform init -reconfigure
        working-directory: step1

      - name: Destroy Terraform resources
        run: terraform destroy -auto-approve
        working-directory: step1
